### ISSUE TITLE
Add new SI unit for velocity (m/s)

### ISSUE THREAD

**Issue by thielec** [samvidav/oxrse_unit_conv#1]
### Name (Abbreviation) of the unit you want to create?

mps

### What is its base SI unit?

new base unit

### Contributor Guide

- [X] I will comply with the [Contributor Guide](../../CONTRIBUTING.md)

### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](../../CODE_OF_CONDUCT.md)

**Comment by samvidav** [comment]
@thielec this is a test comment
